/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ComunicacionesRouteImport } from './routes/comunicaciones'
import { Route as CondicionesRouteImport } from './routes/condiciones'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as InformesRouteImport } from './routes/informes'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ContactosIndexRouteImport } from './routes/contactos.index'
import { Route as ContactosIdRouteImport } from './routes/contactos.$id'
import { Route as ContactosNuevoRouteImport } from './routes/contactos.nuevo'
import { Route as ExpedientesIndexRouteImport } from './routes/expedientes.index'
import { Route as ExpedientesIdRouteImport } from './routes/expedientes.$id'
import { Route as OportunidadesIndexRouteImport } from './routes/oportunidades.index'
import { Route as OportunidadesIdRouteImport } from './routes/oportunidades.$id'
import { Route as OportunidadesNuevaRouteImport } from './routes/oportunidades.nueva'
import { Route as PresupuestosIndexRouteImport } from './routes/presupuestos.index'
import { Route as TareasTaskIdRouteImport } from './routes/tareas.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionesRoute = ComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicionesRoute = CondicionesRouteImport.update({
  id: '/condiciones',
  path: '/condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesRoute = InformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosIndexRoute = ContactosIndexRouteImport.update({
  id: '/contactos/',
  path: '/contactos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosIdRoute = ContactosIdRouteImport.update({
  id: '/contactos/$id',
  path: '/contactos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosNuevoRoute = ContactosNuevoRouteImport.update({
  id: '/contactos/nuevo',
  path: '/contactos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIndexRoute = ExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIdRoute = ExpedientesIdRouteImport.update({
  id: '/expedientes/$id',
  path: '/expedientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesIndexRoute = OportunidadesIndexRouteImport.update({
  id: '/oportunidades/',
  path: '/oportunidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesIdRoute = OportunidadesIdRouteImport.update({
  id: '/oportunidades/$id',
  path: '/oportunidades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesNuevaRoute = OportunidadesNuevaRouteImport.update({
  id: '/oportunidades/nueva',
  path: '/oportunidades/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosIndexRoute = PresupuestosIndexRouteImport.update({
  id: '/presupuestos/',
  path: '/presupuestos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasTaskIdRoute = TareasTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TareasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/condiciones': typeof CondicionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRoute
  '/documentos': typeof DocumentosRoute
  '/facturacion': typeof FacturacionRoute
  '/informes': typeof InformesRoute
  '/notas': typeof NotasRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/tareas': typeof TareasRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/contactos/$id': typeof ContactosIdRoute
  '/contactos/nuevo': typeof ContactosNuevoRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/oportunidades/nueva': typeof OportunidadesNuevaRoute
  '/tareas/$taskId': typeof TareasTaskIdRoute
  '/contactos/': typeof ContactosIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/oportunidades/': typeof OportunidadesIndexRoute
  '/presupuestos/': typeof PresupuestosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/condiciones': typeof CondicionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRoute
  '/documentos': typeof DocumentosRoute
  '/facturacion': typeof FacturacionRoute
  '/informes': typeof InformesRoute
  '/notas': typeof NotasRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/tareas': typeof TareasRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/contactos/$id': typeof ContactosIdRoute
  '/contactos/nuevo': typeof ContactosNuevoRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/oportunidades/nueva': typeof OportunidadesNuevaRoute
  '/tareas/$taskId': typeof TareasTaskIdRoute
  '/contactos': typeof ContactosIndexRoute
  '/expedientes': typeof ExpedientesIndexRoute
  '/oportunidades': typeof OportunidadesIndexRoute
  '/presupuestos': typeof PresupuestosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/condiciones': typeof CondicionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRoute
  '/documentos': typeof DocumentosRoute
  '/facturacion': typeof FacturacionRoute
  '/informes': typeof InformesRoute
  '/notas': typeof NotasRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/tareas': typeof TareasRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/contactos/$id': typeof ContactosIdRoute
  '/contactos/nuevo': typeof ContactosNuevoRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/oportunidades/nueva': typeof OportunidadesNuevaRoute
  '/tareas/$taskId': typeof TareasTaskIdRoute
  '/contactos/': typeof ContactosIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/oportunidades/': typeof OportunidadesIndexRoute
  '/presupuestos/': typeof PresupuestosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/comunicaciones'
    | '/condiciones'
    | '/configuracion'
    | '/cookies'
    | '/crm'
    | '/documentos'
    | '/facturacion'
    | '/informes'
    | '/notas'
    | '/onboarding'
    | '/privacidad'
    | '/tareas'
    | '/terminos'
    | '/contactos/$id'
    | '/contactos/nuevo'
    | '/expedientes/$id'
    | '/oportunidades/$id'
    | '/oportunidades/nueva'
    | '/tareas/$taskId'
    | '/contactos/'
    | '/expedientes/'
    | '/oportunidades/'
    | '/presupuestos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/comunicaciones'
    | '/condiciones'
    | '/configuracion'
    | '/cookies'
    | '/crm'
    | '/documentos'
    | '/facturacion'
    | '/informes'
    | '/notas'
    | '/onboarding'
    | '/privacidad'
    | '/tareas'
    | '/terminos'
    | '/contactos/$id'
    | '/contactos/nuevo'
    | '/expedientes/$id'
    | '/oportunidades/$id'
    | '/oportunidades/nueva'
    | '/tareas/$taskId'
    | '/contactos'
    | '/expedientes'
    | '/oportunidades'
    | '/presupuestos'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/comunicaciones'
    | '/condiciones'
    | '/configuracion'
    | '/cookies'
    | '/crm'
    | '/documentos'
    | '/facturacion'
    | '/informes'
    | '/notas'
    | '/onboarding'
    | '/privacidad'
    | '/tareas'
    | '/terminos'
    | '/contactos/$id'
    | '/contactos/nuevo'
    | '/expedientes/$id'
    | '/oportunidades/$id'
    | '/oportunidades/nueva'
    | '/tareas/$taskId'
    | '/contactos/'
    | '/expedientes/'
    | '/oportunidades/'
    | '/presupuestos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ComunicacionesRoute: typeof ComunicacionesRoute
  CondicionesRoute: typeof CondicionesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CookiesRoute: typeof CookiesRoute
  CrmRoute: typeof CrmRoute
  DocumentosRoute: typeof DocumentosRoute
  FacturacionRoute: typeof FacturacionRoute
  InformesRoute: typeof InformesRoute
  NotasRoute: typeof NotasRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TareasRoute: typeof TareasRouteWithChildren
  TerminosRoute: typeof TerminosRoute
  ContactosIdRoute: typeof ContactosIdRoute
  ContactosNuevoRoute: typeof ContactosNuevoRoute
  ExpedientesIdRoute: typeof ExpedientesIdRoute
  OportunidadesIdRoute: typeof OportunidadesIdRoute
  OportunidadesNuevaRoute: typeof OportunidadesNuevaRoute
  ContactosIndexRoute: typeof ContactosIndexRoute
  ExpedientesIndexRoute: typeof ExpedientesIndexRoute
  OportunidadesIndexRoute: typeof OportunidadesIndexRoute
  PresupuestosIndexRoute: typeof PresupuestosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicaciones': {
      id: '/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof ComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condiciones': {
      id: '/condiciones'
      path: '/condiciones'
      fullPath: '/condiciones'
      preLoaderRoute: typeof CondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes': {
      id: '/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof InformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos/': {
      id: '/contactos/'
      path: '/contactos'
      fullPath: '/contactos/'
      preLoaderRoute: typeof ContactosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos/$id': {
      id: '/contactos/$id'
      path: '/contactos/$id'
      fullPath: '/contactos/$id'
      preLoaderRoute: typeof ContactosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos/nuevo': {
      id: '/contactos/nuevo'
      path: '/contactos/nuevo'
      fullPath: '/contactos/nuevo'
      preLoaderRoute: typeof ContactosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/': {
      id: '/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof ExpedientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/$id': {
      id: '/expedientes/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof ExpedientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/': {
      id: '/oportunidades/'
      path: '/oportunidades'
      fullPath: '/oportunidades/'
      preLoaderRoute: typeof OportunidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/$id': {
      id: '/oportunidades/$id'
      path: '/oportunidades/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof OportunidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/nueva': {
      id: '/oportunidades/nueva'
      path: '/oportunidades/nueva'
      fullPath: '/oportunidades/nueva'
      preLoaderRoute: typeof OportunidadesNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos/': {
      id: '/presupuestos/'
      path: '/presupuestos'
      fullPath: '/presupuestos/'
      preLoaderRoute: typeof PresupuestosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas/$taskId': {
      id: '/tareas/$taskId'
      path: '/$taskId'
      fullPath: '/tareas/$taskId'
      preLoaderRoute: typeof TareasTaskIdRouteImport
      parentRoute: typeof TareasRoute
    }
  }
}

interface TareasRouteChildren {
  TareasTaskIdRoute: typeof TareasTaskIdRoute
}

const TareasRouteChildren: TareasRouteChildren = {
  TareasTaskIdRoute: TareasTaskIdRoute,
}

const TareasRouteWithChildren =
  TareasRoute._addFileChildren(TareasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ComunicacionesRoute: ComunicacionesRoute,
  CondicionesRoute: CondicionesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CookiesRoute: CookiesRoute,
  CrmRoute: CrmRoute,
  DocumentosRoute: DocumentosRoute,
  FacturacionRoute: FacturacionRoute,
  InformesRoute: InformesRoute,
  NotasRoute: NotasRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacidadRoute: PrivacidadRoute,
  TareasRoute: TareasRouteWithChildren,
  TerminosRoute: TerminosRoute,
  ContactosIdRoute: ContactosIdRoute,
  ContactosNuevoRoute: ContactosNuevoRoute,
  ExpedientesIdRoute: ExpedientesIdRoute,
  OportunidadesIdRoute: OportunidadesIdRoute,
  OportunidadesNuevaRoute: OportunidadesNuevaRoute,
  ContactosIndexRoute: ContactosIndexRoute,
  ExpedientesIndexRoute: ExpedientesIndexRoute,
  OportunidadesIndexRoute: OportunidadesIndexRoute,
  PresupuestosIndexRoute: PresupuestosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
