/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActuacionesRouteImport } from './routes/actuaciones'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ComunicacionesRouteImport } from './routes/comunicaciones'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as EjecucionesRouteImport } from './routes/ejecuciones'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as ContactosIndexRouteImport } from './routes/contactos.index'
import { Route as ContactosIdRouteImport } from './routes/contactos.$id'
import { Route as ContactosNuevoRouteImport } from './routes/contactos.nuevo'
import { Route as ExpedientesIndexRouteImport } from './routes/expedientes.index'
import { Route as ExpedientesIdRouteImport } from './routes/expedientes.$id'
import { Route as OportunidadesIndexRouteImport } from './routes/oportunidades.index'
import { Route as OportunidadesIdRouteImport } from './routes/oportunidades.$id'
import { Route as OportunidadesNuevaRouteImport } from './routes/oportunidades.nueva'
import { Route as PresupuestosIndexRouteImport } from './routes/presupuestos.index'
import { Route as PresupuestosIdRouteImport } from './routes/presupuestos.$id'
import { Route as SopsIndexRouteImport } from './routes/sops.index'
import { Route as SopsIdRouteImport } from './routes/sops.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActuacionesRoute = ActuacionesRouteImport.update({
  id: '/actuaciones',
  path: '/actuaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionesRoute = ComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EjecucionesRoute = EjecucionesRouteImport.update({
  id: '/ejecuciones',
  path: '/ejecuciones',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosIndexRoute = ContactosIndexRouteImport.update({
  id: '/contactos/',
  path: '/contactos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosIdRoute = ContactosIdRouteImport.update({
  id: '/contactos/$id',
  path: '/contactos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosNuevoRoute = ContactosNuevoRouteImport.update({
  id: '/contactos/nuevo',
  path: '/contactos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIndexRoute = ExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIdRoute = ExpedientesIdRouteImport.update({
  id: '/expedientes/$id',
  path: '/expedientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesIndexRoute = OportunidadesIndexRouteImport.update({
  id: '/oportunidades/',
  path: '/oportunidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesIdRoute = OportunidadesIdRouteImport.update({
  id: '/oportunidades/$id',
  path: '/oportunidades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesNuevaRoute = OportunidadesNuevaRouteImport.update({
  id: '/oportunidades/nueva',
  path: '/oportunidades/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosIndexRoute = PresupuestosIndexRouteImport.update({
  id: '/presupuestos/',
  path: '/presupuestos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosIdRoute = PresupuestosIdRouteImport.update({
  id: '/presupuestos/$id',
  path: '/presupuestos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SopsIndexRoute = SopsIndexRouteImport.update({
  id: '/sops/',
  path: '/sops/',
  getParentRoute: () => rootRouteImport,
} as any)
const SopsIdRoute = SopsIdRouteImport.update({
  id: '/sops/$id',
  path: '/sops/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actuaciones': typeof ActuacionesRoute
  '/alertas': typeof AlertasRoute
  '/calendario': typeof CalendarioRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/crm': typeof CrmRoute
  '/documentos': typeof DocumentosRoute
  '/ejecuciones': typeof EjecucionesRoute
  '/facturacion': typeof FacturacionRoute
  '/notas': typeof NotasRoute
  '/onboarding': typeof OnboardingRoute
  '/tareas': typeof TareasRoute
  '/contactos/$id': typeof ContactosIdRoute
  '/contactos/nuevo': typeof ContactosNuevoRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/oportunidades/nueva': typeof OportunidadesNuevaRoute
  '/presupuestos/$id': typeof PresupuestosIdRoute
  '/sops/$id': typeof SopsIdRoute
  '/contactos/': typeof ContactosIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/oportunidades/': typeof OportunidadesIndexRoute
  '/presupuestos/': typeof PresupuestosIndexRoute
  '/sops/': typeof SopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actuaciones': typeof ActuacionesRoute
  '/alertas': typeof AlertasRoute
  '/calendario': typeof CalendarioRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/crm': typeof CrmRoute
  '/documentos': typeof DocumentosRoute
  '/ejecuciones': typeof EjecucionesRoute
  '/facturacion': typeof FacturacionRoute
  '/notas': typeof NotasRoute
  '/onboarding': typeof OnboardingRoute
  '/tareas': typeof TareasRoute
  '/contactos/$id': typeof ContactosIdRoute
  '/contactos/nuevo': typeof ContactosNuevoRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/oportunidades/nueva': typeof OportunidadesNuevaRoute
  '/presupuestos/$id': typeof PresupuestosIdRoute
  '/sops/$id': typeof SopsIdRoute
  '/contactos': typeof ContactosIndexRoute
  '/expedientes': typeof ExpedientesIndexRoute
  '/oportunidades': typeof OportunidadesIndexRoute
  '/presupuestos': typeof PresupuestosIndexRoute
  '/sops': typeof SopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actuaciones': typeof ActuacionesRoute
  '/alertas': typeof AlertasRoute
  '/calendario': typeof CalendarioRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/crm': typeof CrmRoute
  '/documentos': typeof DocumentosRoute
  '/ejecuciones': typeof EjecucionesRoute
  '/facturacion': typeof FacturacionRoute
  '/notas': typeof NotasRoute
  '/onboarding': typeof OnboardingRoute
  '/tareas': typeof TareasRoute
  '/contactos/$id': typeof ContactosIdRoute
  '/contactos/nuevo': typeof ContactosNuevoRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
  '/oportunidades/nueva': typeof OportunidadesNuevaRoute
  '/presupuestos/$id': typeof PresupuestosIdRoute
  '/sops/$id': typeof SopsIdRoute
  '/contactos/': typeof ContactosIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
  '/oportunidades/': typeof OportunidadesIndexRoute
  '/presupuestos/': typeof PresupuestosIndexRoute
  '/sops/': typeof SopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actuaciones'
    | '/alertas'
    | '/calendario'
    | '/comunicaciones'
    | '/configuracion'
    | '/crm'
    | '/documentos'
    | '/ejecuciones'
    | '/facturacion'
    | '/notas'
    | '/onboarding'
    | '/tareas'
    | '/contactos/$id'
    | '/contactos/nuevo'
    | '/expedientes/$id'
    | '/oportunidades/$id'
    | '/oportunidades/nueva'
    | '/presupuestos/$id'
    | '/sops/$id'
    | '/contactos/'
    | '/expedientes/'
    | '/oportunidades/'
    | '/presupuestos/'
    | '/sops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actuaciones'
    | '/alertas'
    | '/calendario'
    | '/comunicaciones'
    | '/configuracion'
    | '/crm'
    | '/documentos'
    | '/ejecuciones'
    | '/facturacion'
    | '/notas'
    | '/onboarding'
    | '/tareas'
    | '/contactos/$id'
    | '/contactos/nuevo'
    | '/expedientes/$id'
    | '/oportunidades/$id'
    | '/oportunidades/nueva'
    | '/presupuestos/$id'
    | '/sops/$id'
    | '/contactos'
    | '/expedientes'
    | '/oportunidades'
    | '/presupuestos'
    | '/sops'
  id:
    | '__root__'
    | '/'
    | '/actuaciones'
    | '/alertas'
    | '/calendario'
    | '/comunicaciones'
    | '/configuracion'
    | '/crm'
    | '/documentos'
    | '/ejecuciones'
    | '/facturacion'
    | '/notas'
    | '/onboarding'
    | '/tareas'
    | '/contactos/$id'
    | '/contactos/nuevo'
    | '/expedientes/$id'
    | '/oportunidades/$id'
    | '/oportunidades/nueva'
    | '/presupuestos/$id'
    | '/sops/$id'
    | '/contactos/'
    | '/expedientes/'
    | '/oportunidades/'
    | '/presupuestos/'
    | '/sops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActuacionesRoute: typeof ActuacionesRoute
  AlertasRoute: typeof AlertasRoute
  CalendarioRoute: typeof CalendarioRoute
  ComunicacionesRoute: typeof ComunicacionesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CrmRoute: typeof CrmRoute
  DocumentosRoute: typeof DocumentosRoute
  EjecucionesRoute: typeof EjecucionesRoute
  FacturacionRoute: typeof FacturacionRoute
  NotasRoute: typeof NotasRoute
  OnboardingRoute: typeof OnboardingRoute
  TareasRoute: typeof TareasRoute
  ContactosIdRoute: typeof ContactosIdRoute
  ContactosNuevoRoute: typeof ContactosNuevoRoute
  ExpedientesIdRoute: typeof ExpedientesIdRoute
  OportunidadesIdRoute: typeof OportunidadesIdRoute
  OportunidadesNuevaRoute: typeof OportunidadesNuevaRoute
  PresupuestosIdRoute: typeof PresupuestosIdRoute
  SopsIdRoute: typeof SopsIdRoute
  ContactosIndexRoute: typeof ContactosIndexRoute
  ExpedientesIndexRoute: typeof ExpedientesIndexRoute
  OportunidadesIndexRoute: typeof OportunidadesIndexRoute
  PresupuestosIndexRoute: typeof PresupuestosIndexRoute
  SopsIndexRoute: typeof SopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actuaciones': {
      id: '/actuaciones'
      path: '/actuaciones'
      fullPath: '/actuaciones'
      preLoaderRoute: typeof ActuacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicaciones': {
      id: '/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof ComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejecuciones': {
      id: '/ejecuciones'
      path: '/ejecuciones'
      fullPath: '/ejecuciones'
      preLoaderRoute: typeof EjecucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos/': {
      id: '/contactos/'
      path: '/contactos'
      fullPath: '/contactos/'
      preLoaderRoute: typeof ContactosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos/$id': {
      id: '/contactos/$id'
      path: '/contactos/$id'
      fullPath: '/contactos/$id'
      preLoaderRoute: typeof ContactosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos/nuevo': {
      id: '/contactos/nuevo'
      path: '/contactos/nuevo'
      fullPath: '/contactos/nuevo'
      preLoaderRoute: typeof ContactosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/': {
      id: '/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof ExpedientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/$id': {
      id: '/expedientes/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof ExpedientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/': {
      id: '/oportunidades/'
      path: '/oportunidades'
      fullPath: '/oportunidades/'
      preLoaderRoute: typeof OportunidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/$id': {
      id: '/oportunidades/$id'
      path: '/oportunidades/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof OportunidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/nueva': {
      id: '/oportunidades/nueva'
      path: '/oportunidades/nueva'
      fullPath: '/oportunidades/nueva'
      preLoaderRoute: typeof OportunidadesNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos/': {
      id: '/presupuestos/'
      path: '/presupuestos'
      fullPath: '/presupuestos/'
      preLoaderRoute: typeof PresupuestosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos/$id': {
      id: '/presupuestos/$id'
      path: '/presupuestos/$id'
      fullPath: '/presupuestos/$id'
      preLoaderRoute: typeof PresupuestosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sops/': {
      id: '/sops/'
      path: '/sops'
      fullPath: '/sops/'
      preLoaderRoute: typeof SopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sops/$id': {
      id: '/sops/$id'
      path: '/sops/$id'
      fullPath: '/sops/$id'
      preLoaderRoute: typeof SopsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActuacionesRoute: ActuacionesRoute,
  AlertasRoute: AlertasRoute,
  CalendarioRoute: CalendarioRoute,
  ComunicacionesRoute: ComunicacionesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CrmRoute: CrmRoute,
  DocumentosRoute: DocumentosRoute,
  EjecucionesRoute: EjecucionesRoute,
  FacturacionRoute: FacturacionRoute,
  NotasRoute: NotasRoute,
  OnboardingRoute: OnboardingRoute,
  TareasRoute: TareasRoute,
  ContactosIdRoute: ContactosIdRoute,
  ContactosNuevoRoute: ContactosNuevoRoute,
  ExpedientesIdRoute: ExpedientesIdRoute,
  OportunidadesIdRoute: OportunidadesIdRoute,
  OportunidadesNuevaRoute: OportunidadesNuevaRoute,
  PresupuestosIdRoute: PresupuestosIdRoute,
  SopsIdRoute: SopsIdRoute,
  ContactosIndexRoute: ContactosIndexRoute,
  ExpedientesIndexRoute: ExpedientesIndexRoute,
  OportunidadesIndexRoute: OportunidadesIndexRoute,
  PresupuestosIndexRoute: PresupuestosIndexRoute,
  SopsIndexRoute: SopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
